apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-go-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "k8s-app.in"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-app-service
            port:
              number: 80
